services:
  serverapplication:
    image: serverapplication
    build:
      context: .
      dockerfile: ServerApplication/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ConnectionStrings__DefaultConnection: Server=postgres;Port=5432;User Id=postgres;Password=postgres;Database=postgres;MaxPoolSize=200;Pooling=true;
    depends_on:
      postgres:
          condition: service_healthy
    

  clientapplication:
    image: clientapplication
    build:
      context: .
      dockerfile: ClientApplication/Dockerfile
    ports:
      - "5062:8080"
    environment:
      ServerUrl: http://serverapplication:8080/messages
      
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "1434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
